test_that("use", {
  expect_true("AIDA Data Hub" %in% get_all_providers())
  expect_true("C3SE" %in% get_all_providers())
  expect_true("CSC" %in% get_all_providers())
  expect_true("Code Refinery" %in% get_all_providers())
  expect_true("ENCCS" %in% get_all_providers())
  expect_true("EOSC" %in% get_all_providers())
  expect_true("HPC2N" %in% get_all_providers())
  expect_true("InfraViz" %in% get_all_providers())
  expect_true("LUNARC" %in% get_all_providers())
  expect_true("NAISS" %in% get_all_providers())
  expect_true("NSC" %in% get_all_providers())
  expect_true("PDC" %in% get_all_providers())
  expect_true("SciLifeLab" %in% get_all_providers())
  expect_true("SND" %in% get_all_providers())
  expect_true("Swestore" %in% get_all_providers())
  expect_true("UPPMAX" %in% get_all_providers())

  s <- get_all_providers()
  t <- stringr::str_sort(s)
  expect_equal(s, t)
})
