test_that("use", {

  return()

  # I don't care to provide the home folder to these centers,
  # until 1 person asks me to
  expect_equal(get_provider_homepage("AIDA Data Hub"), "https://datahub.aida.scilifelab.se/")
  expect_equal(get_provider_homepage("C3SE"), "https://www.c3se.chalmers.se/")
  expect_equal(get_provider_homepage("Code Refinery"), "https://coderefinery.org/")
  expect_equal(get_provider_homepage("CSC"), "https://www.lumi.csc.fi/public/")
  expect_equal(get_provider_homepage("Doris SND"), "https://www.snd.se/en/doris-researchers")
  expect_equal(get_provider_homepage("ENCCS"), "...")
  expect_equal(get_provider_homepage("EOSC"), "...")
  expect_equal(get_provider_homepage("FEGA Sweden"), "...")
  expect_equal(get_provider_homepage("GBIF"), "...")
  expect_equal(get_provider_homepage("HPC2N"), "...")
  expect_equal(get_provider_homepage("InfraViz"), "...")
  expect_equal(get_provider_homepage("LUNARC"), "...")
  expect_equal(get_provider_homepage("Mimer"), "...")
  expect_equal(get_provider_homepage("NAISS"), "...")
  expect_equal(get_provider_homepage("NSC"), "...")
  expect_equal(get_provider_homepage("OSCU"), "...")
  expect_equal(get_provider_homepage("PDC"), "...")
  expect_equal(get_provider_homepage("SBDI"), "...")
  expect_equal(get_provider_homepage("SciLifeLab"), "...")
  expect_equal(get_provider_homepage("SITES"), "...")
  expect_equal(get_provider_homepage("SLUBI"), "...")
  expect_equal(get_provider_homepage("SND"), "...")
  expect_equal(get_provider_homepage("Stockholm University"), "...")
  expect_equal(get_provider_homepage("Swestore"), "...")
  expect_equal(get_provider_homepage("University of Gothenburg"), "...")
  expect_equal(get_provider_homepage("UPPMAX"), "https://www.uu.se/en/centre/uppmax.html")
})
