#' Get a testing text for SLUBI courses
#'
#' This text is a patchwork of entries from the SLUBI website
#' collected over time.
#' @return a text to extract the dates from
#' @export
get_slubi_test_courses_text <- function() {
  c(
    "<h1 class=\"title\">Courses</h1>",
    "</div>",
    "",
    "",
    "",
    "<div class=\"quarto-title-meta column-page-right\">",
    "",
    "    ",
    "  ",
    "    ",
    "  </div>",
    "  ",
    "",
    "",
    "</header>",
    "",
    "",
    "<p>Our bioinformatics courses provide training in a variety of methods for analyzing biological data, covering topics such as sequence analysis, population genetics and reproducible research.</p>",
    "<p>Designed for both beginners and seasoned researchers, our courses blend theoretical foundations with practical applications, training participants in the skills needed to tackle complex biological questions.</p>",
    "<p>We also arrange private courses. If you are interested in a topic you can’t find in our list, please <a href=\"./contact.html\">contact us</a>. <br></p>",
    "<div id=\"listing-courses\" class=\"quarto-listing quarto-listing-container-default\">",
    "<div class=\"list quarto-listing-default\">",
    "<div class=\"quarto-post image-left\" data-index=\"0\" data-categories=\"Y291cnNlJTJDdHJhaW5pbmclMkNuZXh0Zmxvdw==\" data-listing-date-sort=\"1756080000000\" data-listing-file-modified-sort=\"1755864295248\" data-listing-date-modified-sort=\"NaN\" data-listing-reading-time-sort=\"1\" data-listing-word-count-sort=\"29\">",
    "<div class=\"thumbnail\"><a href=\"./newsposts/courses/20250825_SIDA_training/index.html\" class=\"no-external\">",
    "",
    "<img loading=\"lazy\" src=\"./newsposts/courses/20250825_SIDA_training/sida.png\" class=\"thumbnail-image\">",
    "",
    "</a></div>",
    "<div class=\"body\">",
    "<h3 class=\"no-anchor listing-title\">",
    "<a href=\"./newsposts/courses/20250825_SIDA_training/index.html\" class=\"no-external\">SIDA training</a>",
    "</h3>",
    "<div class=\"listing-categories\">",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('Y291cnNl'); return false;\">course</div>",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('dHJhaW5pbmc='); return false;\">training</div>",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('bmV4dGZsb3c='); return false;\">nextflow</div>",
    "",
    "</div>",
    "<div class=\"delink listing-description\"><a href=\"./newsposts/courses/20250825_SIDA_training/index.html\" class=\"no-external\">",
    "<p>Reproducible bioinformatics, best practices, Nextflow and nf-core</p>",
    "</a></div>",
    "</div>",
    "<div class=\"metadata\">",
    "<a href=\"./newsposts/courses/20250825_SIDA_training/index.html\" class=\"no-external\">",
    "<div class=\"listing-date\">",
    "Aug 25, 2025",
    "</div>",
    "<div class=\"listing-author\">",
    "SLUBI",
    "</div>",
    "</a>",
    "</div>",
    "</div>",
    "<div class=\"quarto-post image-left\" data-index=\"1\" data-categories=\"Y291cnNlJTJDdHJhaW5pbmclMkNuZXh0Zmxvdw==\" data-listing-date-sort=\"1754006400000\" data-listing-file-modified-sort=\"1755864295252\" data-listing-date-modified-sort=\"NaN\" data-listing-reading-time-sort=\"2\" data-listing-word-count-sort=\"371\">",
    "<div class=\"thumbnail\"><a href=\"./newsposts/courses/20251013_course_RNAseq/index.html\" class=\"no-external\">",
    "",
    "<img loading=\"lazy\" src=\"./newsposts/courses/20251013_course_RNAseq/code.png\" class=\"thumbnail-image\">",
    "",
    "</a></div>",
    "<div class=\"body\">",
    "<h3 class=\"no-anchor listing-title\">",
    "<a href=\"./newsposts/courses/20251013_course_RNAseq/index.html\" class=\"no-external\">Analysis of High Throughput Sequencing RNA-Seq Data</a>",
    "</h3>",
    "<div class=\"listing-categories\">",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('Y291cnNl'); return false;\">course</div>",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('dHJhaW5pbmc='); return false;\">training</div>",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('bmV4dGZsb3c='); return false;\">nextflow</div>",
    "",
    "</div>",
    "<div class=\"delink listing-description\"><a href=\"./newsposts/courses/20251013_course_RNAseq/index.html\" class=\"no-external\">",
    "<p>registration is open now - course dates: October 13th-24th , October 31st, 2025</p>",
    "</a></div>",
    "</div>",
    "<div class=\"metadata\">",
    "<a href=\"./newsposts/courses/20251013_course_RNAseq/index.html\" class=\"no-external\">",
    "<div class=\"listing-date\">",
    "Aug 1, 2025",
    "</div>",
    "<div class=\"listing-author\">",
    "SLUBI",
    "</div>",
    "</a>",
    "</div>",
    "</div>",
    "<div class=\"quarto-post image-left\" data-index=\"2\" data-categories=\"Y291cnNlJTJDTXNjJTJDYnJlZWRpbmc=\" data-listing-date-sort=\"1746662400000\" data-listing-file-modified-sort=\"1755864295270\" data-listing-date-modified-sort=\"NaN\" data-listing-reading-time-sort=\"1\" data-listing-word-count-sort=\"117\">",
    "<div class=\"thumbnail\"><a href=\"./newsposts/courses/2025_course_breeding/index.html\" class=\"no-external\">",
    "",
    "<img loading=\"lazy\" src=\"./newsposts/courses/2025_course_breeding/SLU_210608_2847_spring_barley.jpg\" class=\"thumbnail-image\">",
    "",
    "</a></div>",
    "<div class=\"body\">",
    "<h3 class=\"no-anchor listing-title\">",
    "<a href=\"./newsposts/courses/2025_course_breeding/index.html\" class=\"no-external\">Advanced Plant Breeding and Genetic Resources</a>",
    "</h3>",
    "<div class=\"listing-categories\">",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('Y291cnNl'); return false;\">course</div>",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('TXNj'); return false;\">Msc</div>",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('YnJlZWRpbmc='); return false;\">breeding</div>",
    "",
    "</div>",
    "<div class=\"delink listing-description\"><a href=\"./newsposts/courses/2025_course_breeding/index.html\" class=\"no-external\">",
    "<p>Genetic Variation and Breeding Strategies for Sustainable Agriculture - autumn 2025</p>",
    "</a></div>",
    "</div>",
    "<div class=\"metadata\">",
    "<a href=\"./newsposts/courses/2025_course_breeding/index.html\" class=\"no-external\">",
    "<div class=\"listing-date\">",
    "May 8, 2025",
    "</div>",
    "<div class=\"listing-author\">",
    "SLUBI",
    "</div>",
    "</a>",
    "</div>",
    "</div>",
    "<div class=\"quarto-post image-left\" data-index=\"3\" data-categories=\"Y291cnNlJTJDdHJhaW5pbmclMkNwbGFudHMlMkNicmVlZGluZw==\" data-listing-date-sort=\"1740960000000\" data-listing-file-modified-sort=\"1755864295245\" data-listing-date-modified-sort=\"NaN\" data-listing-reading-time-sort=\"1\" data-listing-word-count-sort=\"101\">",
    "<div class=\"thumbnail\"><a href=\"./newsposts/courses/20250120_course_plant_breeding/index.html\" class=\"no-external\">",
    "",
    "<img loading=\"lazy\" src=\"./newsposts/courses/20250120_course_plant_breeding/image-1.png\" class=\"thumbnail-image\">",
    "",
    "</a></div>",
    "<div class=\"body\">",
    "<h3 class=\"no-anchor listing-title\">",
    "<a href=\"./newsposts/courses/20250120_course_plant_breeding/index.html\" class=\"no-external\">Plant Biology for Breeding and Protection</a>",
    "</h3>",
    "<div class=\"listing-categories\">",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('Y291cnNl'); return false;\">course</div>",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('dHJhaW5pbmc='); return false;\">training</div>",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('cGxhbnRz'); return false;\">plants</div>",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('YnJlZWRpbmc='); return false;\">breeding</div>",
    "",
    "</div>",
    "<div class=\"delink listing-description\"><a href=\"./newsposts/courses/20250120_course_plant_breeding/index.html\" class=\"no-external\">",
    "<p>and how bioinformatics can help you and your plants!</p>",
    "</a></div>",
    "</div>",
    "<div class=\"metadata\">",
    "<a href=\"./newsposts/courses/20250120_course_plant_breeding/index.html\" class=\"no-external\">",
    "<div class=\"listing-date\">",
    "Mar 3, 2025",
    "</div>",
    "<div class=\"listing-author\">",
    "SLUBI",
    "</div>",
    "</a>",
    "</div>",
    "</div>",
    "<div class=\"quarto-post image-left\" data-index=\"4\" data-categories=\"Y291cnNlJTJDdHJhaW5pbmclMkNtZXRhZ2Vub21pY3M=\" data-listing-date-sort=\"1740960000000\" data-listing-file-modified-sort=\"1755864295245\" data-listing-date-modified-sort=\"NaN\" data-listing-reading-time-sort=\"1\" data-listing-word-count-sort=\"78\">",
    "<div class=\"thumbnail\"><a href=\"./newsposts/courses/20250303_course_metagenomics/index.html\" class=\"no-external\">",
    "",
    "<img loading=\"lazy\" src=\"./newsposts/courses/20250303_course_metagenomics/trends.png\" class=\"thumbnail-image\">",
    "",
    "</a></div>",
    "<div class=\"body\">",
    "<h3 class=\"no-anchor listing-title\">",
    "<a href=\"./newsposts/courses/20250303_course_metagenomics/index.html\" class=\"no-external\">Multi-omics analyses of the microbial community</a>",
    "</h3>",
    "<div class=\"listing-categories\">",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('Y291cnNl'); return false;\">course</div>",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('dHJhaW5pbmc='); return false;\">training</div>",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('bWV0YWdlbm9taWNz'); return false;\">metagenomics</div>",
    "",
    "</div>",
    "<div class=\"delink listing-description\"><a href=\"./newsposts/courses/20250303_course_metagenomics/index.html\" class=\"no-external\">",
    "<p>Everything you ever wanted to know about metagenomics.</p>",
    "</a></div>",
    "</div>",
    "<div class=\"metadata\">",
    "<a href=\"./newsposts/courses/20250303_course_metagenomics/index.html\" class=\"no-external\">",
    "<div class=\"listing-date\">",
    "Mar 3, 2025",
    "</div>",
    "<div class=\"listing-author\">",
    "SLUBI",
    "</div>",
    "</a>",
    "</div>",
    "</div>",
    "<div class=\"quarto-post image-left\" data-index=\"5\" data-categories=\"Y291cnNlJTJDdHJhaW5pbmclMkNnaXQlMkNyZXByb2R1Y2liaWxpdHklMkNxdWFydG8lMkNncy12bWFz\" data-listing-date-sort=\"1737331200000\" data-listing-file-modified-sort=\"1755864295240\" data-listing-date-modified-sort=\"NaN\" data-listing-reading-time-sort=\"1\" data-listing-word-count-sort=\"74\">",
    "<div class=\"thumbnail\"><a href=\"./newsposts/courses/20250120_course_illustrations/index.html\" class=\"no-external\">",
    "",
    "<img loading=\"lazy\" src=\"./newsposts/courses/20250120_course_illustrations/ggplot.png\" class=\"thumbnail-image\">",
    "",
    "</a></div>",
    "<div class=\"body\">",
    "<h3 class=\"no-anchor listing-title\">",
    "<a href=\"./newsposts/courses/20250120_course_illustrations/index.html\" class=\"no-external\">Data handling and high-quality illustrations for publications</a>",
    "</h3>",
    "<div class=\"listing-categories\">",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('Y291cnNl'); return false;\">course</div>",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('dHJhaW5pbmc='); return false;\">training</div>",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('Z2l0'); return false;\">git</div>",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('cmVwcm9kdWNpYmlsaXR5'); return false;\">reproducibility</div>",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('cXVhcnRv'); return false;\">quarto</div>",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('Z3Mtdm1hcw=='); return false;\">gs-vmas</div>",
    "",
    "</div>",
    "<div class=\"delink listing-description\"><a href=\"./newsposts/courses/20250120_course_illustrations/index.html\" class=\"no-external\">",
    "<p>A course on how to handle data and create appropriate illustrations for your project.</p>",
    "</a></div>",
    "</div>",
    "<div class=\"metadata\">",
    "<a href=\"./newsposts/courses/20250120_course_illustrations/index.html\" class=\"no-external\">",
    "<div class=\"listing-date\">",
    "Jan 20, 2025",
    "</div>",
    "<div class=\"listing-author\">",
    "SLUBI",
    "</div>",
    "</a>",
    "</div>",
    "</div>",
    "<div class=\"quarto-post image-left\" data-index=\"6\" data-categories=\"Y291cnNlJTJDdHJhaW5pbmclMkNOR1MlMkNyZXByb2R1Y2liaWxpdHklMkNSTkFzZXElMkNncy12bWFz\" data-listing-date-sort=\"1730419200000\" data-listing-file-modified-sort=\"1755864295239\" data-listing-date-modified-sort=\"NaN\" data-listing-reading-time-sort=\"1\" data-listing-word-count-sort=\"65\">",
    "<div class=\"thumbnail\"><a href=\"./newsposts/courses/20241101_course_IntroToBioinf/index.html\" class=\"no-external\">",
    "",
    "<img loading=\"lazy\" src=\"./newsposts/courses/20241101_course_IntroToBioinf/code.png\" class=\"thumbnail-image\">",
    "",
    "</a></div>",
    "<div class=\"body\">",
    "<h3 class=\"no-anchor listing-title\">",
    "<a href=\"./newsposts/courses/20241101_course_IntroToBioinf/index.html\" class=\"no-external\">Introduction to Bioinformatics</a>",
    "</h3>",
    "<div class=\"listing-categories\">",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('Y291cnNl'); return false;\">course</div>",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('dHJhaW5pbmc='); return false;\">training</div>",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('TkdT'); return false;\">NGS</div>",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('cmVwcm9kdWNpYmlsaXR5'); return false;\">reproducibility</div>",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('Uk5Bc2Vx'); return false;\">RNAseq</div>",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('Z3Mtdm1hcw=='); return false;\">gs-vmas</div>",
    "",
    "</div>",
    "<div class=\"delink listing-description\"><a href=\"./newsposts/courses/20241101_course_IntroToBioinf/index.html\" class=\"no-external\">",
    "<p>A course together with SLU’s Graduate School for Veterinary Medicine and Animal Science.</p>",
    "</a></div>",
    "</div>",
    "<div class=\"metadata\">",
    "<a href=\"./newsposts/courses/20241101_course_IntroToBioinf/index.html\" class=\"no-external\">",
    "<div class=\"listing-date\">",
    "Nov 1, 2024",
    "</div>",
    "<div class=\"listing-author\">",
    "SLUBI",
    "</div>",
    "</a>",
    "</div>",
    "</div>",
    "<div class=\"quarto-post image-left\" data-index=\"7\" data-categories=\"Y291cnNlJTJDdHJhaW5pbmclMkNnaXQlMkNyZXByb2R1Y2liaWxpdHklMkNncy12bWFz\" data-listing-date-sort=\"1729468800000\" data-listing-file-modified-sort=\"1755864295236\" data-listing-date-modified-sort=\"NaN\" data-listing-reading-time-sort=\"1\" data-listing-word-count-sort=\"49\">",
    "<div class=\"thumbnail\"><a href=\"./newsposts/courses/20241021_course_reproducible/index.html\" class=\"no-external\">",
    "",
    "<img loading=\"lazy\" src=\"./newsposts/courses/20241021_course_reproducible/Rlogo.svg\" class=\"thumbnail-image\">",
    "",
    "</a></div>",
    "<div class=\"body\">",
    "<h3 class=\"no-anchor listing-title\">",
    "<a href=\"./newsposts/courses/20241021_course_reproducible/index.html\" class=\"no-external\">Reproducibility in Research with a focus on data analysis using the program R</a>",
    "</h3>",
    "<div class=\"listing-categories\">",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('Y291cnNl'); return false;\">course</div>",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('dHJhaW5pbmc='); return false;\">training</div>",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('Z2l0'); return false;\">git</div>",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('cmVwcm9kdWNpYmlsaXR5'); return false;\">reproducibility</div>",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('Z3Mtdm1hcw=='); return false;\">gs-vmas</div>",
    "",
    "</div>",
    "<div class=\"delink listing-description\"><a href=\"./newsposts/courses/20241021_course_reproducible/index.html\" class=\"no-external\">",
    "<p>Tips, tricks and tools for making your research more reproducible.</p>",
    "</a></div>",
    "</div>",
    "<div class=\"metadata\">",
    "<a href=\"./newsposts/courses/20241021_course_reproducible/index.html\" class=\"no-external\">",
    "<div class=\"listing-date\">",
    "Oct 21, 2024",
    "</div>",
    "<div class=\"listing-author\">",
    "SLUBI",
    "</div>",
    "</a>",
    "</div>",
    "</div>",
    "<div class=\"quarto-post image-left\" data-index=\"8\" data-categories=\"Y291cnNlJTJDdHJhaW5pbmclMkNuZXh0Zmxvdw==\" data-listing-date-sort=\"1728259200000\" data-listing-file-modified-sort=\"1755864295236\" data-listing-date-modified-sort=\"NaN\" data-listing-reading-time-sort=\"1\" data-listing-word-count-sort=\"49\">",
    "<div class=\"thumbnail\"><a href=\"./newsposts/courses/20241007_course_RNAseq/index.html\" class=\"no-external\">",
    "",
    "<img loading=\"lazy\" src=\"./newsposts/courses/20241007_course_RNAseq/code.png\" class=\"thumbnail-image\">",
    "",
    "</a></div>",
    "<div class=\"body\">",
    "<h3 class=\"no-anchor listing-title\">",
    "<a href=\"./newsposts/courses/20241007_course_RNAseq/index.html\" class=\"no-external\">Analysis of High Throughput Sequencing RNA-Seq Data</a>",
    "</h3>",
    "<div class=\"listing-categories\">",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('Y291cnNl'); return false;\">course</div>",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('dHJhaW5pbmc='); return false;\">training</div>",
    "",
    "<div class=\"listing-category\" onclick=\"window.quartoListingCategory('bmV4dGZsb3c='); return false;\">nextflow</div>",
    "",
    "</div>",
    "<div class=\"delink listing-description\"><a href=\"./newsposts/courses/20241007_course_RNAseq/index.html\" class=\"no-external\">",
    "<p>The history of RNA sequencing, and modern ways to analyse the data.</p>",
    "</a></div>",
    "</div>",
    "<div class=\"metadata\">",
    "<a href=\"./newsposts/courses/20241007_course_RNAseq/index.html\" class=\"no-external\">",
    "<div class=\"listing-date\">",
    "Oct 7, 2024",
    "</div>",
    "<div class=\"listing-author\">",
    "SLUBI",
    "</div>",
    "</a>",
    "</div>",
    "</div>"
  )
}
